name: uberscousin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  cloud_firestore: ^4.13.2
  firebase_auth: ^4.14.0
  firebase_core: ^2.22.0
  firebase_ui_auth: ^1.10.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  intl: ^0.18.1
  image_picker: ^1.0.4
  accordion: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
   - assets/images/facebook.jpg
   - assets/images/google.jpg
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: fonts/PlusJakartaSans-Italic-VariableFont_wght.ttf
        - asset: fonts/PlusJakartaSans-VariableFont_wght.ttf
          style: italic

